<link href="{{ asset('css/bootstrap.min.css') }}" rel='stylesheet' />
<link href="{{ asset('font-awesome/css/font-awesome.css') }}" rel='stylesheet' />
<link href="{{ asset('css/plugins/iCheck/custom.css') }}" rel='stylesheet' />
<link href="{{ asset('css/plugins/fullcalendar/fullcalendar.css') }}" rel='stylesheet' />
<link href="{{ asset('css/plugins/fullcalendar/fullcalendar.print.css') }}" rel='stylesheet' media='print'/>
<link href="{{ asset('css/plugins/dataTables/datatables.min.css') }}" rel='stylesheet' />
<link href="{{ asset('css/animate.css') }}" rel='stylesheet' />
<link href="{{ asset('css/style.css') }}" rel='stylesheet' />
<link href="{{ asset('css/plugins/chosen/chosen.css') }}" rel='stylesheet' />
<link href="{{ asset('css/plugins/sweetalert/sweetalert.css') }}" rel='stylesheet' />